file:
  path: ${ROOT_PATH}/raw_data
  name: ${FILE_NAME}
  supported:
    - csv
    - parquet

  data:
    structure:
      - position: x_axis
        column: generated_on
        type: datetime64[ns]
      - position: y_axis
        column: blend_cost_diff #dlvd_price
        type: float64
      - position: label
        column: load_month
        type: datetime64[ns]
      - position: others
        column: display_name
        type: object
        value: RBOB

    outliers:
      - z_score

  output:
    path: ${ROOT_PATH}
    extension: ${OUTPUT_EXTENSION}

logger:
  level: INFO